//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 12:33:41 PM ART 
//


package SAYAV2.SAYAV2.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import SAYAV2.SAYAV2.mensajeria.Mensaje;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element ref="{http://www.example.org/Mensaje}Mensaje" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mensaje"
})
@XmlRootElement(name = "MensajesPendientes", namespace = "http://www.example.org/MensajesPendientes")
public class MensajesPendientes {

    @XmlElement(name = "Mensaje")
    protected List<Mensaje> mensaje;
    
    

    public MensajesPendientes() {
		super();
		this.mensaje = new ArrayList<Mensaje>();
	}


    public boolean addMensaje(Mensaje mensaje){
    	if(this.mensaje.contains(mensaje)){
    		return false;
    	}
    	return this.mensaje.add(mensaje);
    }

	/**
     * Gets the value of the mensaje property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mensaje property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMensaje().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mensaje }
     * 
     * 
     */
    public List<Mensaje> getMensaje() {
        if (mensaje == null) {
            mensaje = new ArrayList<Mensaje>();
        }
        return this.mensaje;
    }


	public Mensaje getMensaje(String id) {
		for(Mensaje m: this.mensaje){
			if(m.getId().equals(id)){
				return m;
			}
		}
		return null;
	}

}
