//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 11:36:17 PM ART 
//


package SAYAV2.SAYAV2.model;

import javax.xml.bind.annotation.XmlRegistry;

import SAYAV2.SAYAV2.notificacion.Votacion;
import SAYAV2.SAYAV2.notificacion.Votaciones;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the SAYAV2.SAYAV2.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: SAYAV2.SAYAV2.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Votaciones }
     * 
     */
    public Votaciones createVotaciones() {
        return new Votaciones();
    }
    
    /**
     * Create an instance of {@link Votaciones }
     * 
     */
    public Notificaciones createNotificaciones() {
        return new Notificaciones();
    }
    
    /**
     * Create an instance of {@link Votaciones }
     * 
     */
    public Configurator createConfigurator() {
        return new Configurator();
    }

    /**
     * Create an instance of {@link Votacion }
     * 
     */
    public Votacion createVotacion() {
        return new Votacion();
    }

    /**
     * Create an instance of {@link Usuario }
     * 
     */
    public Usuario createUsuario() {
        return new Usuario();
    }

    /**
     * Create an instance of {@link DispositivoM }
     * 
     */
    public DispositivoM createDispositivoM() {
        return new DispositivoM();
    }

    /**
     * Create an instance of {@link Sector }
     * 
     */
    public Sector createSector() {
        return new Sector();
    }

    /**
     * Create an instance of {@link Grupo }
     * 
     */
    public Grupo createGrupo() {
        return new Grupo();
    }

    /**
     * Create an instance of {@link Peer }
     * 
     */
    public Peer createPeer() {
        return new Peer();
    }

}
