//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 11:36:17 PM ART 
//


package SAYAV2.SAYAV2.model;

import java.util.UUID;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Peer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Peer"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://www.example.org/response}Peer"/&gt;
 *         &lt;element name="Direccion" type="{http://www.w3.org/2001/XMLSchema}Peer"/&gt;
 *         &lt;element name="Puerto" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Estado" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Peer", propOrder = {
    "id",
    "direccion",
    "puerto",
    "estado"
})
public class Peer {

    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "Direccion", required = true)
    protected String direccion;
    @XmlElement(name = "Puerto")
    protected int puerto;
    @XmlElement(name = "Estado")
    protected boolean estado;
    
    public Peer() {
		super();
		this.id = UUID.randomUUID().toString();
	}

	public Peer(String direccion) {
		super();
		this.id = UUID.randomUUID().toString();
		this.direccion = direccion;
	}


    public Peer(String subdominio, Integer puerto) {
    	super();
		this.id = UUID.randomUUID().toString();
		this.direccion = subdominio;
		this.puerto = puerto;
	}

	/**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the direccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * Sets the value of the direccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccion(String value) {
        this.direccion = value;
    }

    /**
     * Gets the value of the puerto property.
     * 
     */
    public int getPuerto() {
        return puerto;
    }

    /**
     * Sets the value of the puerto property.
     * 
     */
    public void setPuerto(int value) {
        this.puerto = value;
    }

    /**
     * Gets the value of the estado property.
     * 
     */
    public boolean isEstado() {
        return estado;
    }

    /**
     * Sets the value of the estado property.
     * 
     */
    public void setEstado(boolean value) {
        this.estado = value;
    }
    @Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((direccion == null) ? 0 : direccion.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Peer other = (Peer) obj;
		if (direccion == null) {
			if (other.direccion != null)
				return false;
		} else if (!direccion.equals(other.direccion))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Peer [id=" + id + ", direccion=" + direccion + ", puerto="+ puerto 
				+ ", estado=" + estado;
	}

}
