//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.20 at 05:53:44 PM ART 
//

package SAYAV2.SAYAV2.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="Nombre" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="Apellido" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="Telefono" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *           &lt;element name="Direccion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="Subdominio" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="Contraseña" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="Salt" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="AlarmaHabilitada" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element name="DispositivosMoviles" type="{http://www.example.org/UsuarioXMLSchema}DispositivoM" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Sectores" type="{http://www.example.org/UsuarioXMLSchema}Sector" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Grupos" type="{http://www.example.org/UsuarioXMLSchema}Grupo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "nombre", "apellido", "telefono", "email", "direccion", "subdominio", "contraseña",
		"salt", "alarmaHabilitada", "dispositivosMoviles", "sectores", "grupos" })
@XmlRootElement(name = "Usuario")
public class Usuario {

	@XmlElement(name = "Nombre")
	protected String nombre;
	@XmlElement(name = "Apellido")
	protected String apellido;
	@XmlElement(name = "Telefono")
	protected String telefono;
	@XmlElement(name = "Email")
	protected String email;
	@XmlElement(name = "Direccion")
	protected String direccion;
	@XmlElement(name = "Subdominio")
	protected String subdominio;
	@XmlElement(name = "Contraseña")
	protected String contraseña;
	@XmlElement(name = "Salt")
	protected String salt;
	@XmlElement(name = "AlarmaHabilitada")
	protected Boolean alarmaHabilitada;
	@XmlElement(name = "DispositivosMoviles")
	protected List<DispositivoM> dispositivosMoviles;
	@XmlElement(name = "Sectores")
	protected List<Sector> sectores;
	@XmlElement(name = "Grupos")
	protected List<Grupo> grupos;

	public Usuario() {
		super();
		this.alarmaHabilitada = true;
		this.dispositivosMoviles = new ArrayList<DispositivoM>();
		this.sectores = new ArrayList<Sector>();
		this.grupos = new ArrayList<Grupo>();
	}

	/**
	 * Gets the value of the nombre property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * Sets the value of the nombre property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNombre(String value) {
		this.nombre = value;
	}

	/**
	 * Gets the value of the apellido property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getApellido() {
		return apellido;
	}

	/**
	 * Sets the value of the apellido property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setApellido(String value) {
		this.apellido = value;
	}

	/**
	 * Gets the value of the telefono property.
	 * 
	 * @return possible object is {@link Long }
	 * 
	 */
	public String getTelefono() {
		return telefono;
	}

	/**
	 * Sets the value of the telefono property.
	 * 
	 * @param value
	 *            allowed object is {@link Long }
	 * 
	 */
	public void setTelefono(String value) {
		this.telefono = value;
	}

	/**
	 * Gets the value of the email property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * Sets the value of the email property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEmail(String value) {
		this.email = value;
	}

	/**
	 * Gets the value of the direccion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDireccion() {
		return direccion;
	}

	/**
	 * Sets the value of the direccion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDireccion(String value) {
		this.direccion = value;
	}

	/**
	 * Gets the value of the subdominio property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubdominio() {
		return subdominio;
	}

	/**
	 * Sets the value of the subdominio property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubdominio(String value) {
		this.subdominio = value;
	}

	/**
	 * Gets the value of the contraseña property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContraseña() {
		return contraseña;
	}

	/**
	 * Sets the value of the contraseña property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setContraseña(String value) {
		this.contraseña = value;
	}

	/**
	 * Gets the value of the salt property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * Sets the value of the salt property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSalt(String value) {
		this.salt = value;
	}

	/**
	 * Gets the value of the alarmaHabilitada property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isAlarmaHabilitada() {
		return alarmaHabilitada;
	}

	/**
	 * Sets the value of the alarmaHabilitada property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setAlarmaHabilitada(Boolean value) {
		this.alarmaHabilitada = value;
	}

	/**
	 * Gets the value of the dispositivosMoviles property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the dispositivosMoviles property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDispositivosMoviles().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link DispositivoM }
	 * 
	 * 
	 */
	public List<DispositivoM> getDispositivosMoviles() {
		if (dispositivosMoviles == null) {
			dispositivosMoviles = new ArrayList<DispositivoM>();
		}
		return this.dispositivosMoviles;
	}

	public Boolean getAlarmaHabilitada() {
		return alarmaHabilitada;
	}

	public void setDispositivosMoviles(List<DispositivoM> dispositivosMoviles) {
		this.dispositivosMoviles = dispositivosMoviles;
	}

	public void setSectores(List<Sector> sectores) {
		this.sectores = sectores;
	}

	public void setGrupos(List<Grupo> grupos) {
		this.grupos = grupos;
	}

	/**
	 * Gets the value of the sectores property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the sectores property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSectores().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Sector }
	 * 
	 * 
	 */
	public List<Sector> getSectores() {
		if (sectores == null) {
			sectores = new ArrayList<Sector>();
		}
		return this.sectores;
	}

	/**
	 * Gets the value of the grupos property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the grupos property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getGrupos().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Grupo }
	 * 
	 * 
	 */
	public List<Grupo> getGrupos() {
		if (grupos == null) {
			grupos = new ArrayList<Grupo>();
		}
		return this.grupos;
	}

	public boolean existSector(String nombre) {
		Sector s = new Sector();
		s.setNombre(nombre);
		if (this.sectores.contains(s))
			return true;
		return false;
	}

	public Sector getSector(String nombre) {
		Sector nuevo = new Sector();
		nuevo.setNombre(nombre);
		for (Sector s : this.sectores) {
			if (s.equals(nuevo))
				return s;
		}
		return null;
	}

	public DispositivoM getDispositivo(String numero) {
		DispositivoM nuevo = new DispositivoM();
		nuevo.setNumero(numero);
		for (DispositivoM d : this.dispositivosMoviles) {
			if (d.equals(nuevo))
				return nuevo;
		}
		return null;
	}

	public boolean addGrupo(Grupo grupo) {
		if (this.grupos.contains(grupo)) {
			return false;
		}
		return this.grupos.add(grupo);
	}

	public Grupo getSingleGrupo(String nombre){
		Grupo nuevo = new Grupo(nombre);
		for(Grupo g: this.grupos){
			if(g.equals(nuevo)){
				return g;
			}
		}
		return null;
	}
	
	@Override
	public String toString() {
		return "Usuario [nombre=" + nombre + ", apellido=" + apellido + ", telefono=" + telefono + "]";
	}

}
