//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 11:36:17 PM ART 
//


package SAYAV2.SAYAV2.model;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="Nombre" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="Apellido" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="NombreDeUsuario" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *           &lt;element name="Direccion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="Subdominio" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="Contraseña" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="Salt" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="AlarmaHabilitada" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element name="DispositivosMoviles" type="{http://www.example.org/UsuarioXMLSchema}DispositivoM" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Sectores" type="{http://www.example.org/UsuarioXMLSchema}Sector" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Grupos" type="{http://www.example.org/UsuarioXMLSchema}Grupo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nombre",
    "apellido",
    "nombreDeUsuario",
    "email",
    "direccion",
    "subdominio",
    "contraseña",
    "salt",
    "alarmaHabilitada",
    "dispositivosMoviles",
    "sectores",
    "grupos"
})
@XmlRootElement(name = "Usuario" ,namespace="http://www.example.org/Mensaje")
public class Usuario {

    @XmlElement(name = "Nombre")
    protected String nombre;
    @XmlElement(name = "Apellido")
    protected String apellido;
    @XmlElement(name = "NombreDeUsuario")
    protected String nombreDeUsuario;
    @XmlElement(name = "Email")
    protected String email;
    @XmlElement(name = "Direccion")
    protected String direccion;
    @XmlElement(name = "Subdominio")
    protected String subdominio;
    @XmlElement(name = "Contraseña")
    protected String contraseña;
    @XmlElement(name = "Salt")
    protected String salt;
    @XmlElement(name = "AlarmaHabilitada")
    protected Boolean alarmaHabilitada;
    @XmlElement(name = "DispositivosMoviles")
    protected List<DispositivoM> dispositivosMoviles;
    @XmlElement(name = "Sectores")
    protected List<Sector> sectores;
    @XmlElement(name = "Grupos")
    protected List<Grupo> grupos;

    public Usuario() {
		super();
		this.dispositivosMoviles = new LinkedList<DispositivoM>();
		this.sectores = new LinkedList<Sector>();
		this.grupos = new LinkedList<Grupo>();
		this.alarmaHabilitada = true;
	}

	/**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the apellido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApellido() {
        return apellido;
    }

    /**
     * Sets the value of the apellido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApellido(String value) {
        this.apellido = value;
    }

    /**
     * Gets the value of the nombreDeUsuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreDeUsuario() {
        return nombreDeUsuario;
    }

    /**
     * Sets the value of the nombreDeUsuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreDeUsuario(String value) {
        this.nombreDeUsuario = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the direccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * Sets the value of the direccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccion(String value) {
        this.direccion = value;
    }

    /**
     * Gets the value of the subdominio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubdominio() {
        return subdominio;
    }

    /**
     * Sets the value of the subdominio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubdominio(String value) {
        this.subdominio = value;
    }

    /**
     * Gets the value of the contraseña property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContraseña() {
        return contraseña;
    }

    /**
     * Sets the value of the contraseña property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContraseña(String value) {
        this.contraseña = value;
    }

    /**
     * Gets the value of the salt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalt() {
        return salt;
    }

    /**
     * Sets the value of the salt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalt(String value) {
        this.salt = value;
    }

    /**
     * Gets the value of the alarmaHabilitada property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAlarmaHabilitada() {
        return alarmaHabilitada;
    }

    /**
     * Sets the value of the alarmaHabilitada property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAlarmaHabilitada(Boolean value) {
        this.alarmaHabilitada = value;
    }

    /**
     * Gets the value of the dispositivosMoviles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dispositivosMoviles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDispositivosMoviles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DispositivoM }
     * 
     * 
     */
    public List<DispositivoM> getDispositivosMoviles() {
        if (dispositivosMoviles == null) {
            dispositivosMoviles = new ArrayList<DispositivoM>();
        }
        return this.dispositivosMoviles;
    }

    /**
     * Gets the value of the sectores property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sectores property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSectores().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sector }
     * 
     * 
     */
    public List<Sector> getSectores() {
        if (sectores == null) {
            sectores = new ArrayList<Sector>();
        }
        return this.sectores;
    }

    /**
     * Gets the value of the grupos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grupos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrupos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Grupo }
     * 
     * 
     */
    public List<Grupo> getGrupos() {
        if (grupos == null) {
            grupos = new ArrayList<Grupo>();
        }
        return this.grupos;
    }

    public boolean existSector(String nombre) {
		Sector s = new Sector();
		s.setNombre(nombre);
		if (this.sectores.contains(s))
			return true;
		return false;
	}

	public Sector getSector(String nombre) {
		Sector nuevo = new Sector();
		nuevo.setNombre(nombre);
		for (Sector s : this.sectores) {
			if (s.equals(nuevo))
				return s;
		}
		return null;
	}

	public DispositivoM getDispositivo(String numero) {
		DispositivoM nuevo = new DispositivoM();
		nuevo.setNumero(numero);
		for (DispositivoM d : this.dispositivosMoviles) {
			if (d.equals(nuevo))
				return nuevo;
		}
		return null;
	}

	
	public boolean addGrupo(Grupo grupo) {
		if (this.grupos.contains(grupo)) {
			return false;
		}
		if(getSingleGrupoByName(grupo.getNombre()) != null){
			return false;
		}
		return this.grupos.add(grupo);
	}
	
	public boolean addGrupo(String grupo) {
		Grupo nuevoGrupo = new Grupo(grupo);
		if (this.grupos.contains(nuevoGrupo)) {
			return false;
		}
		if(getSingleGrupoByName(grupo) != null){
			return false;
		}
		return this.grupos.add(nuevoGrupo);
	}
	

	public Grupo getSingleGrupoByName(String nombre){
		for(Grupo g: this.grupos){
			if(g.getNombre().equals(nombre)){
				return g;
			}
		}
		return null;
	}
	
	public Grupo getSingleGrupoById(String id){
		Grupo nuevo = new Grupo(nombre);
		nuevo.setId(id);
		for(Grupo g: this.grupos){
			if(g.equals(nuevo)){
				return g;
			}
		}
		return null;
	}


	public List<String> getTokens() {
		// TODO Auto-generated method stub
		List<String> registration_ids = new ArrayList<String>();
		for(DispositivoM d: this.dispositivosMoviles){
			if(!d.token.isEmpty())
				registration_ids.add(d.token);
		}
		return registration_ids;
	}

	public boolean removeGrupo(String groupName) {
		Grupo grupo = new Grupo(groupName);
		return this.grupos.remove(grupo);
	}

	public Usuario(String nombre, String apellido, String nombreDeUsuario, String email, String direccion,
			String subdominio, String contraseña, String salt, Boolean alarmaHabilitada,
			List<DispositivoM> dispositivosMoviles, List<Sector> sectores, List<Grupo> grupos) {
		super();
		this.nombre = nombre;
		this.apellido = apellido;
		this.nombreDeUsuario = nombreDeUsuario;
		this.email = email;
		this.direccion = direccion;
		this.subdominio = subdominio;
		this.contraseña = contraseña;
		this.salt = salt;
		this.alarmaHabilitada = alarmaHabilitada;
		this.dispositivosMoviles = dispositivosMoviles;
		this.sectores = sectores;
		this.grupos = grupos;
	}
	
	
}
