//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.04 at 01:00:56 PM ART 
//


package SAYAV2.SAYAV2.notificacion;

import java.util.UUID;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import SAYAV2.SAYAV2.model.Grupo;
import SAYAV2.SAYAV2.model.Peer;


/**
 * <p>Java class for Votacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Votacion"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;        
 *         &lt;element name="Miembro" type="{http://www.example.org/UsuarioXMLSchema}Peer"/&gt;
 *         &lt;element name="Grupo" type="{http://www.example.org/UsuarioXMLSchema}Grupo"/&gt;
 *         &lt;element name="VotantesAFavor" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="VotantesEnContra" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Finalizo" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Votacion", namespace = "http://www.example.org/Votaciones", propOrder = {
    "id",
    "miembro",
    "grupo",
    "votantesAFavor",
    "votantesEnContra",
    "finalizo"
})
public class Votacion {
	private String id;
    @XmlElement(name = "Miembro", namespace = "http://www.example.org/Votaciones", required = true)
    protected Peer miembro;
    @XmlElement(name = "Grupo", namespace = "http://www.example.org/Votaciones", required = true)
    protected Grupo grupo;
    @XmlElement(name = "VotantesAFavor", namespace = "http://www.example.org/Votaciones")
    protected int votantesAFavor;
    @XmlElement(name = "VotantesEnContra", namespace = "http://www.example.org/Votaciones")
    protected int votantesEnContra;
    @XmlElement(name = "Finalizo", namespace = "http://www.example.org/Votaciones")
    protected boolean finalizo;

    
    public Votacion() {
		super();
		this.setId(UUID.randomUUID().toString());

	}

	public Votacion(Peer miembro, Grupo grupo) {
		super();
		this.setId(UUID.randomUUID().toString());
		this.miembro = miembro;
		this.grupo = grupo;
		this.votantesAFavor = 0;
		this.votantesEnContra = 0;
		this.finalizo = false;
	}

	/**
     * Gets the value of the miembro property.
     * 
     * @return
     *     possible object is
     *     {@link Peer }
     *     
     */
    public Peer getMiembro() {
        return miembro;
    }

    /**
     * Sets the value of the miembro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Peer }
     *     
     */
    public void setMiembro(Peer value) {
        this.miembro = value;
    }

    /**
     * Gets the value of the grupo property.
     * 
     * @return
     *     possible object is
     *     {@link Grupo }
     *     
     */
    public Grupo getGrupo() {
        return grupo;
    }

    /**
     * Sets the value of the grupo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Grupo }
     *     
     */
    public void setGrupo(Grupo value) {
        this.grupo = value;
    }

    /**
     * Gets the value of the votantesAFavor property.
     * 
     */
    public int getVotantesAFavor() {
        return votantesAFavor;
    }

    /**
     * Sets the value of the votantesAFavor property.
     * 
     */
    public void setVotantesAFavor(int value) {
        this.votantesAFavor = value;
    }

    /**
     * Gets the value of the votantesEnContra property.
     * 
     */
    public int getVotantesEnContra() {
        return votantesEnContra;
    }

    /**
     * Sets the value of the votantesEnContra property.
     * 
     */
    public void setVotantesEnContra(int value) {
        this.votantesEnContra = value;
    }

    /**
     * Gets the value of the finalizo property.
     * 
     */
    public boolean isFinalizo() {
        return finalizo;
    }

    /**
     * Sets the value of the finalizo property.
     * 
     */
    public void setFinalizo(boolean value) {
        this.finalizo = value;
    }

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	public String getPorcentajeAFavor(){
		
		double porcentaje = this.votantesAFavor * 100 / this.grupo.getPeers().size();
		
		return porcentaje + "%";
	}
	
	public String getPorcentajeEnContra(){
		
		double porcentaje = this.votantesEnContra * 100 / this.grupo.getPeers().size();
		
		return porcentaje + "%";
	}
	
	public String getPorcentajeVotantes(){
		
		double porcentaje = (this.votantesEnContra + this.votantesAFavor) * 100 / this.grupo.getPeers().size();
		
		return porcentaje + "%";
	}



}
