//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.04 at 01:00:56 PM ART 
//


package SAYAV2.SAYAV2.notificacion;

import java.util.LinkedList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import SAYAV2.SAYAV2.model.Grupo;
import SAYAV2.SAYAV2.model.Peer;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Votaciones" type="{http://www.example.org/Votaciones}Votacion" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "votaciones"
})
@XmlRootElement(name = "Votaciones", namespace = "http://www.example.org/Votaciones")
public class Votaciones {

    @XmlElement(name = "Votaciones", namespace = "http://www.example.org/Votaciones")
    protected List<Votacion> votaciones;
    
    

    public Votaciones() {
		super();
		this.votaciones = new LinkedList<Votacion>();
	}



	/**
     * Gets the value of the votaciones property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the votaciones property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVotaciones().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Votacion }
     * 
     * 
     */
    public List<Votacion> getVotaciones() {
        return this.votaciones;
    }
    
    public boolean addVotacion(Votacion votacion){
    	if(this.votaciones.contains(votacion)){
    		return false;
    	}
    	return this.votaciones.add(votacion);
    }



	public Votacion getVotacion(Grupo grupo, Peer miembro) {
		for(Votacion votacion: this.votaciones){
			if(votacion.getMiembro().equals(miembro) && votacion.grupoId.equals(grupo.getId())){
				return votacion;
			}
		}
		return null;
	}



	@Override
	public String toString() {
		return "Votaciones [votaciones=" + votaciones + "]";
	}
	
	

}
